#!/usr/bin/env bash
# Script that displays information about subdomains

domain_info () {
	answer_section=$(dig "$1" | grep -A1 'ANSWER SECTION' | tail -n 1)

	sub_domain=$(echo "$answer_section" | awk '{print $1;}' FS=.) 
	record_type=$(echo "$answer_section" | awk '{print $4;}')
	ip_address=$(echo "$answer_section" | awk '{print $5}')

	echo "The subdomain $sub_domain is a $record_type record and points to $ip_address" 
}

if [ $# -eq 1 ]
then
	domain_info "www.$1" 
	domain_info "lb-01.$1"
	domain_info "web-01.$1"
	domain_info "web-02.$1"
elif [ $# -eq 2 ]
then
	domain_info "$2.$1"
fi
