#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_not_found.html > /dev/null
sed -i "46i error_page 404 /404_not_found.html;" /etc/nginx/sites-available/default
service nginx restart
