#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 234560-web-01 54.172.62.42:80 check
        server 234560-web-02 54.196.36.55:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
