#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# Prints the username, id, and home path for the user

while read -r LINE
do
    echo "$LINE" | cut -d ":" -f 1,3,6
done </etc/passwd
