#!/usr/bin/env bash
# This script prints "Best School" 10 times with while loop
# Print "Hi" on the 9th iteration

i=1
while ((i <= 10))
do
    echo "Best School"
    if ((i == 9))
    then
	echo "Hi"
    fi
    ((i++))
done
