#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes
# Prints hours from 0 to 12
# Prints minutes from 1 to 59

i=0

while ((i <= 12))
do
    echo "Hour: " $i
    j=1
    while ((j <= 59))
    do
	echo $j
	((j++))
    done
    ((i++))
done
